# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_execution_client_work_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='channel',
            field=models.CharField(
                choices=[
                    ('modern_trade', 'Modern Trade'),
                    ('global_trade', 'Global Trade'),
                ],
                default='modern_trade',
                help_text='Select whether this client belongs to Modern Trade or Global Trade',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='brand',
            name='program_plan',
            field=models.TextField(blank=True, help_text='Global Trade program plan for this brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='customer_reach',
            field=models.TextField(blank=True, help_text='Global Trade customer reach or intended audience footprint'),
        ),
        migrations.AddField(
            model_name='brand',
            name='program_objective',
            field=models.TextField(blank=True, help_text='Global Trade program objective'),
        ),
        migrations.AddField(
            model_name='brand',
            name='program_execution',
            field=models.TextField(blank=True, help_text='Global Trade program execution'),
        ),
        migrations.AddField(
            model_name='brand',
            name='program_achievement',
            field=models.TextField(blank=True, help_text='Global Trade program achievement or result'),
        ),
    ]
