# Generated by Codex on 2026-05-20

from django.db import migrations, models
import django.db.models.deletion


def move_gt_fields_to_programs(apps, schema_editor):
    Brand = apps.get_model('core', 'Brand')
    BrandProgram = apps.get_model('core', 'BrandProgram')

    for brand in Brand.objects.select_related('client').all():
        if brand.client.channel != 'global_trade':
            continue

        has_program_content = any([
            brand.program_plan,
            brand.customer_reach,
            brand.program_objective,
            brand.program_execution,
            brand.program_achievement,
        ])
        if not has_program_content:
            continue

        BrandProgram.objects.create(
            brand=brand,
            title='Main Program',
            program_plan=brand.program_plan,
            customer_reach=brand.customer_reach,
            objective=brand.program_objective,
            execution_strategy=brand.program_execution,
            achievement=brand.program_achievement,
            order=0,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_client_channel_brand_gt_program_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Program name or activity title', max_length=200)),
                ('program_plan', models.TextField(blank=True, help_text='Plan for this Global Trade program')),
                ('customer_reach', models.TextField(blank=True, help_text='Customer reach for this program')),
                ('objective', models.TextField(blank=True, help_text='Objective for this program')),
                ('execution_strategy', models.TextField(blank=True, help_text='Execution strategy for this program')),
                ('achievement', models.TextField(blank=True, help_text='Achievement or result for this program')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display priority order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.brand')),
            ],
            options={
                'verbose_name': 'Brand Program',
                'verbose_name_plural': 'Brand Programs',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RunPython(move_gt_fields_to_programs, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='brand',
            name='customer_reach',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='program_achievement',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='program_execution',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='program_objective',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='program_plan',
        ),
    ]
