# Generated by Django 4.2.11 on 2026-05-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_brandprogram_move_gt_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='execution',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
